openapi: 3.0.1
info:
  title: 注文取得API
  version: 1.0.0
servers:
  - url: "https://api.example.com"
paths:
  /api/v1/order/{entrySheetNumber}:
    post:
      summary: 注文取得（GETオーバーロード）
      operationId: getOrderOverloaded
      parameters:
        - name: entrySheetNumber
          in: path
          description: 申込書番号
          required: true
          schema:
            type: string
            maxLength: 14
        - name: page
          in: query
          description: ページ番号
          required: true
          schema:
            type: string
            maxLength: 4
        - name: pageSize
          in: query
          description: １ページ当たりの表示件数
          required: true
          schema:
            type: string
            maxLength: 3
        - name: X-HTTP-Method-Override
          in: header
          description: 機密情報をGETメソッドで取得するリスクを避けるため、POSTメソッドを使用し、`X-HTTP-Method-Override` ヘッダーでGETメソッドとして処理。
          required: true
          schema:
            type: string
            enum: [GET]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                dummy:
                  type: string
                  example: "This is just to satisfy POST request body"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    type: object
                    properties:
                      contractType:
                        type: string
                      sbbAgencyCode:
                        type: string
                      sbmShopCode:
                        type: string
                      entryDate:
                        type: string
                        format: date
                      contractorNameSeiKana:
                        type: string
                      contractorNameMeiKana:
                        type: string
                      mysbUrlNotificationMethod:
                        type: string
                      mobilePhoneNumber:
                        type: string
                      mailAddress:
                        type: string
                      orderStatus:
                        type: string
                      idDocInfo:
                        type: object
                        properties:
                          idDocRegistrationStatus:
                            type: string
                          idDocReviewNgCertType:
                            type: string
                          idDocReviewNgCertReason:
                            type: string
                          idDocReviewNgCertReasonAlt:
                            type: string
                          idDocReviewNgCertType2:
                            type: string
                          idDocReviewNgCert2Reason:
                            type: string
                          idDocReviewNgCert2ReasonAlt:
                            type: string
                          idDocReviewNgAdditionalCertType:
                            type: string
                          idDocReviewNgAdditionalCertReason:
